add generic auth method
kubecube-io/KubeCube pull request #19
Opened 2021-08-12 04:59 UTC by JiahuiZhao11

Ⅰ. Describe what this PR does
1. add generic auth method
2. modify auth middleware logic
3. fix read audit service address
Ⅱ. Does this pull request fix one issue?
Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.
Ⅳ. Describe how to verify it
Ⅴ. Special notes for reviews

2021-08-16 02:06 UTC, weilaaa commented on cmd/cube/app/options/options.go
> +	"github.com/kubecube-io/kubecube/pkg/authentication"
The import of the package needs to follow the specification

2021-08-16 02:18 UTC, weilaaa commented on pkg/authentication/identityprovider/generic/generic.go
> +	URL    string `json:"url,omitempty" yaml:"url"`
why  do we need yaml tag

2021-08-16 02:19 UTC, weilaaa commented on pkg/authentication/identityprovider/generic/generic.go
> +	URL    string `json:"url,omitempty" yaml:"url"`
why  do we need yaml tag

2021-08-16 02:21 UTC, weilaaa commented on pkg/authentication/identityprovider/generic/generic.go
> +func (g *GenericIdentity) GetUserEmail() string {
add comment if generic has no email

2021-08-16 02:23 UTC, weilaaa commented on pkg/authentication/identityprovider/generic/generic.go
> +		return nil, nil
return nil error here?

2021-08-16 02:27 UTC, weilaaa commented on pkg/authentication/identityprovider/generic/generic.go
> +	username := respMap["name"]
what if response body has no that key "name"?

2021-08-16 02:27 UTC, weilaaa commented on pkg/authentication/identityprovider/generic/generic.go
> +		Username: username.(string),
what if username is not type of string?

2021-08-16 02:34 UTC, weilaaa approved these changes
It would be better if you could add some comments

2021-08-16 05:58 UTC, fusida requested changes
something need to be change

2021-08-16 05:58 UTC, fusida commented on pkg/authentication/identityprovider/generic/generic.go
> +		clog.Error("new http request err: %s", err)
%s not match error type

2021-08-16 05:58 UTC, fusida commented on pkg/authentication/identityprovider/generic/generic.go
> +		clog.Error("request to generic auth error: %s", err)
%s not match error type

2021-08-16 05:58 UTC, fusida commented on pkg/authentication/identityprovider/ldap/ldap.go
> +	LdapLoginNameConfig  string `yaml:"ldapLoginNameConfig,omitempty"`
这一行与下一行不一样，逗号后面是否有空格要统一

2021-08-16 05:58 UTC, fusida commented on pkg/authentication/identityprovider/ldap/ldap.go
> +		clog.Error("%s", err)
%s != error type

2021-08-16 05:58 UTC, fusida commented on pkg/authentication/identityprovider/ldap/ldap.go
> +		clog.Error("search ldap err: %s", err)
%s != error type

2021-08-16 05:58 UTC, fusida commented on pkg/authentication/identityprovider/ldap/ldap.go
> +		clog.Error("bind ldap server by admin password error: %s", err)
%s != error type

2021-08-16 05:58 UTC, fusida commented on pkg/utils/env/env.go
>  	if r == "" {
if h == "" ?

2021-08-16 05:58 UTC, fusida commented on pkg/apiserver/middlewares/audit/audit.go
>  		clog.Error("[audit] create http request error: %s", err)
%s

2021-08-16 06:38 UTC, fusida approved these changes
LGTM

2021-08-16 13:24 UTC, Fish-pro commented on pkg/apiserver/cubeapi/key/handle.go
> +	"github.com/kubecube-io/kubecube/pkg/authentication/authenticators/token"
导入包位置不对

2021-08-17 02:32 UTC, zhujf1989 commented on pkg/apiserver/cubeapi/key/handle.go
> +	"github.com/kubecube-io/kubecube/pkg/authentication/authenticators/token"
> The import package is in the wrong location

Thanks for review! It seems like a bug of `gofmt`. We'll use `goimport` later.

//cc please fix it manually this time @JiahuiZhao11

2021-08-17 02:53 UTC, JiahuiZhao11 commented on pkg/apiserver/cubeapi/key/handle.go
> +	"github.com/kubecube-io/kubecube/pkg/authentication/authenticators/token"
Have adjusted the order, thanks.

2021-08-17 11:35 UTC, weilaaa approved these changes
modify package import

2021-08-17 12:05 UTC, fusida approved these changes
LGTM

2021-08-17 12:55 UTC, merged