[WIP] make audit report international
kubecube-io/KubeCube pull request #80
Opened 2021-12-28 07:05 UTC by JiahuiZhao11

Ⅰ. Describe what this PR does
add international util & make audit report international
Ⅱ. Does this pull request fix one issue?

Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.

Ⅳ. Describe how to verify it

Ⅴ. Special notes for reviews

2021-12-28 07:34 UTC, weilaaa commented
better use multi instance to optimize it

2021-12-30 02:23 UTC, weilaaa commented on pkg/apiserver/apiserver.go
> +	middlewares.SetUpMiddlewares(router, cfg.Gi18nManagers)
set Gi18nManagers into cfg

2021-12-30 02:26 UTC, weilaaa commented on pkg/apiserver/middlewares/audit/audit.go
> +	enT := h.Managers.GetInstants("en")
consider if use const to cover string

2021-12-30 02:26 UTC, weilaaa commented on pkg/apiserver/middlewares/audit/audit.go
> +	t := h.Managers.GetInstants(env.AuditLanguage())
move it to handler init

2021-12-30 02:27 UTC, weilaaa commented on pkg/apiserver/middlewares/audit/audit_test.go
> +	"github.com/kubecube-io/kubecube/pkg/utils/international"
move this pkg bellow

2021-12-30 02:27 UTC, weilaaa commented on pkg/apiserver/middlewares/audit/audit_test.go
> +	enInstance.SetPath("/Users/zhaojiahui/code/go/kubecube/KubeCube/i18n")
do not use absolute path here

2021-12-30 02:33 UTC, weilaaa commented on pkg/utils/international/manager.go
> +		languages = defaultOptions
if configmap not found, i18n file less

2021-12-30 02:34 UTC, weilaaa commented on pkg/utils/international/manager.go
> +	defer m.lock.Unlock()
newManager func do not need lock

2021-12-30 02:35 UTC, weilaaa commented on pkg/utils/international/manager.go
> +	g.lock.RLock()
put m := g.Managers[language] init lock state

2021-12-30 02:36 UTC, weilaaa requested changes
need fix something

2021-12-30 04:31 UTC, JiahuiZhao11 commented on pkg/apiserver/apiserver.go
> +	middlewares.SetUpMiddlewares(router, cfg.Gi18nManagers)
do not modify temporarily

2022-01-05 06:21 UTC, weilaaa commented on pkg/apiserver/middlewares/audit/audit.go
> +	metadata, ok := body["metadata"].(map[string]interface{})
what if there is no key "metadata"

2022-01-05 06:22 UTC, weilaaa commented on pkg/apiserver/middlewares/audit/audit.go
> +	name, ok := metadata["name"].(string)
as same as before

2022-01-05 06:22 UTC, weilaaa requested changes
need fix

2022-01-05 07:17 UTC, weilaaa approved these changes
LGTM

2022-01-05 07:48 UTC, weilaaa approved these changes
LGTM

2022-01-05 08:48 UTC, merged