fix audit middleware to a goroutine
kubecube-io/KubeCube pull request #90
Opened 2022-01-20 08:00 UTC by JiahuiZhao11

Ⅰ. Describe what this PR does
fix audit middleware to a goroutine
Ⅱ. Does this pull request fix one issue?

Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.

Ⅳ. Describe how to verify it

Ⅴ. Special notes for reviews

2022-01-20 09:21 UTC, fusida requested changes

2022-01-20 09:21 UTC, fusida commented on pkg/apiserver/middlewares/audit/audit.go
> +	if t == nil {
did this work?

2022-01-20 09:25 UTC, fusida approved these changes
LGTM

2022-01-21 03:27 UTC, weilaaa approved these changes
LGTMg

2022-01-25 03:37 UTC, merged