Feature restapi rbac
kubecube-io/KubeCube pull request #92
Opened 2022-01-21 02:16 UTC by tiancandevloper

Ⅰ. Describe what this PR does
add the access to restapi
Ⅱ. Does this pull request fix one issue?
no
Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.
the test need deploy it and add user,only test cases not work
Ⅳ. Describe how to verify it
if you have a sever, you can use  kubectl auth can-i to verify it
Ⅴ. Special notes for reviews

2022-01-21 05:51 UTC, fusida requested changes

2022-01-21 05:51 UTC, fusida commented on pkg/apiserver/middlewares/auth/rbac.go
> +		clog.Info("user %v check permission success, path %v")
%v need match params

2022-01-21 05:51 UTC, fusida commented on pkg/utils/access/access.go
> +	if cli==nil{
code need go fmt

2022-01-21 05:51 UTC, fusida commented on pkg/apiserver/cubeapi/cluster/handler.go
> +		response.FailReturn(c, errcode.AuthenticateError)
need Forbidden 403 not 401

2022-02-11 06:13 UTC, fusida approved these changes
LGTM

2022-02-16 02:48 UTC, weilaaa commented on pkg/apiserver/middlewares/auth/rbac.go
> +	h := NewHandler()
We should NewHandler once when register it.

2022-02-16 02:53 UTC, weilaaa commented on pkg/utils/access/access.go
> +func AllowAccess(cluster string, c *gin.Context, operator string, object client.Object) bool {
use http.Requst

2022-02-16 02:53 UTC, weilaaa commented on pkg/utils/access/access.go
> +func IsSelf(c *gin.Context, username string) bool {
use http.Request

2022-02-16 02:53 UTC, weilaaa requested changes
need fix

2022-02-17 07:29 UTC, weilaaa approved these changes
LGTM

2022-03-03 03:26 UTC, JiahuiZhao11 reviewed
LGTM

2022-03-15 02:41 UTC, merged